#define __TARGET_TITLE__ TSW
#define __TARGET_TITLE_CN__ 魔塔
#define __DAT_DIR__ Savedat
#define __TSW_DIR__ TSW1.2r3
#define __TSW_INI__ TSW12.INI
#define __TSW_INI_BAK__ TSW12.BAK.INI

#define IDS_ERR_WINAPI 300
#define IDS_ERR_GAME_PATH_MISSING 301
#define IDS_ERR_SAVEDIR_MISSING 302
#define IDS_ERR_WINDIR_INVALID 303
#define IDS_ERR_APPDIR_INVALID 304
#define IDS_ERR_SAVEDIR_INVALID 305
#define IDS_ERR_CANT_DELETE 306
#define IDS_ERR_CANT_RENAME 307
#define IDS_ERR_CANT_WRITE 308
#define IDS_ERR_CANT_RUN 309
#define IDS_ERR_APP_RUNNING 310
#define IDS_ERR_SELECTION 311
#define IDS_INFO_INITIALIZE 315
#define IDS_INFO_INITIALIZE_OK 316


#define __MAKESTRING(x) __MAKESTRING1(__##x##__)
#define __MAKESTRING1(...) __MAKESTRING2(__VA_ARGS__)
#define __MAKESTRING2(x) #x

#define TARGET_TITLE __MAKESTRING(TARGET_TITLE) // "TSW", similar below
#define TARGET_TITLE_CN __MAKESTRING(TARGET_TITLE_CN)
#define DAT_DIR __MAKESTRING(DAT_DIR)
#define TSW_DIR __MAKESTRING(TSW_DIR)
#define TSW_INI __MAKESTRING(TSW_INI)
#define TSW_INI_BAK __MAKESTRING(TSW_INI_BAK)

